import random
print("This is a Dice stimulator by Kanika Mahal")
x = "y"
while x == "y":
      x = random.randint(1,6)
      if x ==1:
            print("____________")
            print("|          |")
            print("|          |")
            print("|     O    |")
            print("|          |")
            print("|          |")
            print("____________")
      if x ==2:
            print("____________")
            print("|          |")
            print("|          |")
            print("| O      O |")
            print("|          |")
            print("|          |")
            print("____________")
      if x== 3:
            print("____________")
            print("|          |")
            print("|     O    |")
            print("|     O    |")
            print("|     O    |")
            print("|          |")
            print("____________")
      if x== 4:
            print("____________")
            print("| O     O  |")
            print("|          |")
            print("|          |")
            print("|          |")
            print("| O      O |")
            print("____________")
      if x==5:
            print("____________")
            print("| O     O  |")
            print("|          |")
            print("|     O    |")
            print("|          |")
            print("| O      O |")
            print("____________")
      if x==6:
            print("____________")
            print("| O  O  O  |")
            print("|          |")
            print("|          |")
            print("|          |")
            print("| O  O  O  |")
            print("____________")
      x= input("Press y to roll again")